MovieReview/config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  get 'users/show'
devise_for :users, controllers: { registrations: 'registrations' }


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :movies do
  	collection do 
  		get :search
  	end
    collection do 
      get :autocomplete
    end
  	
  	resources :reviews
  end

  root 'movies#index'
end

MovieReview/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

MovieReview/app/models/category.rb
class Category < ApplicationRecord
	has_many :movies
end

MovieReview/app/models/movie.rb
class Movie < ApplicationRecord
	searchkick word_middle: [:title]

	def search_data
		{
		title: title
		}
	end
	belongs_to :user
	belongs_to :category
	has_many :reviews

	#Paperclip
	#has_attached_file :movie_img, styles: { movie_index: "250x250>", movie_show: "700x700>" }, default_url: "/images/:style/missing.png"
  	#validates_attachment_content_type :movie_img, content_type: /\Aimage\/.*\z/
end

MovieReview/app/models/review.rb
class Review < ApplicationRecord
	belongs_to :movie
	belongs_to :user

	validates :movie_id, :uniqueness => {:scope => :user_id}
end

MovieReview/app/models/user.rb
class User < ApplicationRecord
		searchkick word_middle: [:firstname, :surname]

	def search_data
		{
		firstname: firstname,
		surname: surname
		}
	end
	serialize :follows, Array
	has_many :movies
	has_many :reviews
	has_attached_file :user_img, :styles => { user_index: "250x250>", user_show: "900x900>" }, default_url: "/images/:style/missing.png"
 	validates_attachment_content_type :user_img, content_type: /\Aimage\/.*\z/
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  
end

MovieReview/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

MovieReview/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	before_action :authenticate_user!, only: [:new, :edit, :destroy]
	before_action :find_movie, only: [:show, :edit, :update, :destroy]
	

	def index

		if params[:category].blank?
			@movie = Movie.all.order("created_at DESC").page(params[:page]).per(9)


		else
			@category_id = Category.find_by(name: params[:category]).id
			@movie = Movie.where(:category_id => @category_id).order("created_at DESC").page(params[:page]).per(9)
		end
		@image = {}
		@average = {}
		@movie.each do |movie|
			omdb = RestClient.get('https://www.omdbapi.com/', {params: {t: movie.title,y: movie.year, apikey: '847f91b9'}})
			omdb=JSON.parse(omdb)
			@image[movie.id] = omdb['Poster']
			if movie.reviews.blank?
				@average[movie.id] = 0
			else
				sum = 0
				i = 0
				movie.reviews.each do |review|
				 	next if review.rating.zero?
				 	sum += review.rating
				 	i += 1 
				end
				average = i.zero? ? 0 : sum.to_f / i 
				@average[movie.id] = average.round(2)
			end
		end
	end

	def search

		
		if params[:title].present?
			@movie= Movie.search(params[:title], fields: [:title], misspellings: {below: 5,edit_distance: 2} ,page: params[:page], per_page: 9)
			

		else
			@movie = Movie.all

		end
				@image = {}
		@average = {}
		@movie.each do |movie|
			omdb = RestClient.get('https://www.omdbapi.com/', {params: {t: movie.title,y: movie.year, apikey: '847f91b9'}})
			omdb=JSON.parse(omdb)
			@image[movie.id] = omdb['Poster']
			if movie.reviews.blank?
				@average[movie.id] = 0
			else
				sum = 0
				i = 0
				movie.reviews.each do |review|
				 	next if review.rating.zero?
				 	sum += review.rating
				 	i += 1 
				end
				average = i.zero? ? 0 : sum.to_f / i 
				@average[movie.id] = average.round(2)
			end
		end

	end 

	def autocomplete
	render json: Movie.search(params[:title], {
      fields: ["title"],
      match: :word_start,
      load: false,
      misspellings: {below: 5}
    }).map(&:title)
	end

	def show
		if @movie.reviews.blank?
			@average = 0
		else
			sum = 0
			i = 0		
			@movie.reviews.each do |review|
		 		next if review.rating.zero?
		 		sum += review.rating
				i += 1 
			end
			average = i.zero? ? 0 : sum.to_f / i 
			@average = average.round(2)
		end
		omdb = RestClient.get('https://www.omdbapi.com/', {params: {t: @movie.title,y:@movie.year, apikey: '847f91b9'}})
		omdb=JSON.parse(omdb)
		@image = omdb['Poster']
		@director = omdb['Director']
		@year = omdb['Year']
		@genre = omdb['Genre']
		@description = omdb['Plot']
		@runtime = omdb['Runtime']
		@actors = omdb['Actors']
		@imdbID = omdb['imdbID']

		@rev = @movie.reviews.page(params[:page]).per(6)

	end

	def new
		@movie = current_user.movies.build
		@categories =Category.all.map{ |c| [c.name, c.id] }
	end

	def edit
		@categories =Category.all.map{ |c| [c.name, c.id] }
	end

	def update
		@movie.category_id = params[:category_id]
		if @movie.update(movie_params)
			redirect_to movie_path(@movie)
		else

			render 'edit'
		end
	end

	def destroy
		@movie.reviews.destroy_all
		@movie.destroy
		redirect_to root_path
		

	end

	def create
		@movie = current_user.movies.build(movie_params)
		@movie.category_id = params[:category_id]

		if @movie.save
			redirect_to root_path
		else
			render 'new'
		end
	end
	
	def find_movie
		@movie = Movie.find(params[:id])
	end


	private
	def movie_params
		params.require(:movie).permit(:title, :category_id, :year)
	end
end

MovieReview/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:firstname, :surname, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:firstname, :surname, :email, :password, :password_confirmation, :current_password, :user_img, :about_me)
  end
end

MovieReview/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
before_action :authenticate_user!, only: [:new, :edit, :destroy]
	
before_action :find_movie
before_action :find_review , only:[:edit, :update, :destroy]

	def new
		@review = Review.new
	end

	def create
		create_params = review_params
		create_params[:rating] = 0 if review_params[:rating] == ''
		@error = ''
		@review = Review.new(create_params)
		@review.movie_id = @movie.id
		@review.user_id = current_user.id
		if @review.save
			redirect_to movie_path(@movie)
		else
			@error = 'You already reviewd this movie!'
			render 'new'
		end
	end

	def edit
	end
	

	def update
		update_params = review_params
		update_params[:rating] = 0 if review_params[:rating] == ''
		if @review.update(update_params)
			redirect_to movie_path(@movie)
		else
			render 'edit'
		end
	end

	def destroy
		@review.destroy
		redirect_to movie_path(@movie)
	end

	private
		def review_params
			params.require(:review).permit(:rating, :comment)
		end

		def find_movie
			@movie = Movie.find(params[:movie_id])
		end

		def find_review
			@review= Review.find(params[:id])
		end

		def find_user
			@user=User.find(params[:user_id])
		end
end

MovieReview/app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :find_user , only: [:show, :edit, :update, :destroy]
before_action :authenticate_user!
  def index
  	
    if params[:query].present?
      @users= User.search(params[:query], fields: [:firstname, :surname])
      

    else
      @users = User.all

    end
  end

  def show
    @reviews=Review.where(:user_id => @user.id).page(params[:page]).per(3)
    @follows = []
    @user.follows.each do |id|
      @follows << User.find(id) unless User.where(id: id).empty?
    end
  end
 
 def update

	if @user.update_attributes(secure_params)
		redirect_to user_path
	else
		redirect_to movie_path, :notice => 'wrong'
	end
  
  private secure_params
  	params.require(:user).permit(:role)
  end

  def find_user
    @user=User.find(params[:id])
  end  

end

MovieReview/app/helpers/application_helper.rb
module ApplicationHelper
end

MovieReview/app/helpers/movies_helper.rb
module MoviesHelper
end

MovieReview/app/helpers/reviews_helper.rb
module ReviewsHelper
end

MovieReview/app/helpers/users_helper.rb
module UsersHelper
end

MovieReview/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
      <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>MovieReview</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">
        <link href="sticky-footer-navbar.css" rel="stylesheet">
  
</head>
<body>

  <nav class="navbar navbar-inverse ">

    <div class="container-static">

      <div class="navbar-header">

        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
          </button>
        <%= link_to "Movie Review", root_path, class: "navbar-brand" %>
      </div>
      

      <div id="navbar" class="navbar-collapse collapse ">
      <ul class="nav navbar-nav">

        <% if user_signed_in? %>
         <li><%= link_to "Add movie", new_movie_path %></li>
      <% end %>


      <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categories <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <% Category.all.each do |category| %>
              <li class="<%= 'active' if params[:category] == category.name %>">
                 <%= link_to category.name, movies_path(category: category.name), class: "link" %>
              </li>
            <% end %>

          </ul>  
      </li>

      <li >
      <%= form_tag search_movies_path, method: :get, class: "navbar-form navbar-left", role: "search," do%>
      
        <%= text_field_tag :title, params[:title],id: "title" , placeholder: "Movie search" ,class: "form-control", size: "10"%>
        <%= submit_tag "Search", name: nil, class: "btn btn-default"%>
        
      
      <% end%> 
      </li>
        
      </ul >
    
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown-header"><hr></li>

      <% if user_signed_in? %>
      <li><%= link_to "Users", users_path %></li>
        <% if current_user.user_img.file? %>
          <li>
             <%= image_tag current_user.user_img.url(:user_index), :class => "profile_tumb"%>
           </li>
        <% else %>
          <li><img class='profile_tumb' src="/assets/default-user.png" >
          </li>
        <% end %>

       <% @id = current_user.id  %>
       
       <li><%= link_to current_user.firstname, user_path(current_user) %></li>

        <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Log in", new_user_session_path %></li>
      <% end %>
          <% if !user_signed_in? %>
      <li><%= link_to "Sign up", new_user_registration_path %></li>
    <% end %>
      

        
      </ul>
    </div>
  

  </nav>





<div class="container">
<%= yield %>
</div>

    <footer role="contentinfo">
      
        <span class="text-muted">Készítette: Biczók Márton </span>
    
    </footer>


</body>


<script>
  $('.average').raty({
    readOnly: true,
    path: '/assets/',
    score: function() {
      return $(this).attr('data-score')
    }
  });
</script>

<script>
    $(document).scroll(function() {
        $("#navbar").toggleClass("tiny",$(document). scrollTop() > 50);
    });
</script>


<script src="https://unpkg.com/axios/dist/axios.min.js"></script>


</html>

MovieReview/app/views/movies/_form.html.erb
<%= simple_form_for @movie, :html =>{ :multipart =>true} do |f| %>
<%= select_tag(:category_id, options_for_select(@categories))%>
<%= f.input :title, label: "Movie title", :required => true %>

<%= f.button :submit %>
<% end  %>

MovieReview/app/views/movies/edit.html.erb
<h1>Edit movie</h1>
<%= simple_form_for @movie, :html =>{ :multipart =>true } do |f| %>
<p><b>Category: </b><%= f.select :category_id, @categories%></p>

<%= f.input :title, label: "Movie title", :required => true %>

<%= f.select :year, (1900..2017) %>


<%= f.button :submit %>
<% end  %>

MovieReview/app/views/movies/index.html.erb
<h1 calss="current-category" > <%=params[:category] %> Movies</h1>
<div class="row">
	
<% @movie.each do |movie|%>

	<div class="col-md-4">
		<a href="/movies/<%=movie.id%>">
		<div class="movie_frame">
			<div class="index_img">
				<% if @image[movie.id].nil? %>

					<img class='movie<%=movie.id%>' src="assets/notavailable.jpg" height="200" width= "auto">
				<% else%>
					<img class='movie<%=movie.id%>' src="<%= @image[movie.id] %>" height="200" width= "auto">
				<% end %>
				
			</div>
			
			<div class="inside">
	 			<%=movie.title%> <% if movie.year.nil? %> 
	 			<%else%>
	 			(<%= movie.year%>)
	 			<%end%>
	 			<div class="average" data-score=<%= @average[movie.id] %> ></div>

	 		</div>
	 		

		</div>
		</a>
	</div>

<%end%>
</div>
<%= paginate @movie %>
<script>
	$('.average').raty({
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		},
		path: '/assets/'
	});
</script>



MovieReview/app/views/movies/new.html.erb
<a href="/movies/">
<img class='backbutton' src="/assets/back.jpg" >
</a>
<h1>New movie</h1>

<%= render 'form' %>

MovieReview/app/views/movies/search.html.erb
<div class="row">
	<% @movie.each do |movie| %>

	<div class="col-md-4">
		<a href="/movies/<%=movie.id%>">
		<div class="movie_frame">
			<div class="index_img">
				<% if @image[movie.id].nil? %>

					<img class='movie<%=movie.id%>' src="/assets/notavailable.jpg" height="200" width= "auto">
				<% else%>
					<img class='movie<%=movie.id%>' src="<%= @image[movie.id] %>" height="200" width= "auto">
				<% end %>
					
					
				
			</div>
			
			<div class="inside">
	 			<%=movie.title%>
	 			<div class="average" data-score=<%= @average[movie.id] %> ></div>

	 		</div>
	 		

		</div>
		</a>
	</div>
	<% end %>
	
</div>

<%= paginate @movie %>

MovieReview/app/views/movies/show.html.erb
<a href="/movies/">
	<img class='backbutton' src="/assets/back.jpg" >
</a>

<div class="row">
	<div class="col-md-4">

		<% if @image.nil?  %>

					<img class='cover' src="/assets/notavailable.jpg" height="200" width= "auto">
				<% else%>
					<img class='cover' src="<%= @image %>" height="200" width= "auto">
				<% end %>

		<a href="http://www.imdb.com/title/<%=@imdbID%>/">
					<img class="imdb_logo" src="/assets/imdb-logo.png">
					
				</a>
		<%if current_user %>
		<div> <%=link_to "Add review", new_movie_review_path(@movie) %></div>
		<%end%>
		<% if user_signed_in? %>
			<% id = current_user.id  %>
			<%if @movie.user_id == current_user.id || id==1 %>
				<%= link_to "Edit",edit_movie_path(@movie)%>
				<p><%=  %> </p>
				<%= link_to "Delete",movie_path(@movie), method: :delete,data: {confirm: "Are you sure?"} %>
			<% end %>
		<% end %>
		
	</div>
	<div class="col-md-4">
		<h2><%= @movie.title %></h2>
		<h4><%= @runtime%></h4>
		<h3>Director: <%= @director %></h3>
		<h4> <%= @year %></h4>
		<h4>Category: <%= @genre %></h4>
		<h3>Average Rating:</h3>
			<div class="review-rating" data-score=<%= @average %>></div>
			<span> <%= @movie.reviews.count%> rating (<%= @average %>)</span>
		
		<h4>Actors: <%= @actors%></h4>
		<p class="movie-desc"> <%=@description%></p>
		
	</div>

	<div class="col-md-4" id="movie_reviews">
		<%= paginate @rev %>
		<%= render @rev%>
	</div>


<div>



</div>
</div>

<script>
	$('.review-rating').raty({
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		},
		path: '/assets/'
	});
</script>


MovieReview/app/views/reviews/_form.html.erb
<%= simple_form_for ([@movie, @movie.reviews.build]) do |f|%>
	<div><p><%= @error %></p></div>
	<div id="rating-form">
		<label>Rating:</label>
	</div>
	<%=f.input :comment %>
	<%=f.button :submit %>
<% end %>

<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

MovieReview/app/views/reviews/_review.html.erb
<table class = "review">
	<tr>
	<th id="asd" >
		<% if review.user.user_img.file? %>
          <li>
             <%= image_tag review.user.user_img.url(:user_index), :class => "review_tumb"%>
           </li>
        <% else %>
          <li><img class='profile_tumb' src="/assets/default-user.png" >
          </li>
        <% end %>
		
	</th>


<th >

<%= link_to review.user.firstname + " " + review.user.surname, user_path(review.user.id) %>
<div class = "review-rating" data-score= "<%= review.rating %>" ></div>
<p class="review_comment"><%= review.comment %></p>

<% if user_signed_in? %>
	<% id = current_user.id  %>
	<%if review.user_id == current_user.id || id==1 %>
		<%= link_to "Edit", edit_movie_review_path(review.movie,review)%>
		<%= link_to "Delete",movie_review_path(review.movie,review), method: :delete,data: {confirm: "Are you sure?"} %>
	<% end %>
<% end %>
</th>
</tr>
</table>

MovieReview/app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= simple_form_for ([@movie,@review]) do |f| %>
	<div id="rating-form">
		<label>Rating:</label>
	</div>
	<%=f.input :comment %>
	<%=f.button :submit %>
<% end %>

<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

MovieReview/app/views/reviews/new.html.erb
<h1>New rew.</h1>
<%= render 'form' %>

MovieReview/app/views/users/index.html.erb
<div class="row">
<%= form_tag users_index_path, method: :get, class: "navbar-form navbar-left", role: "search," do%>
      
        <%= text_field_tag :query, params[:query] , placeholder: "User search" ,class: "form-control" %>
        <%= submit_tag "Search", name: nil, class: "btn btn-default"%>
        
      
      <% end%> 
  </div>
<div class="row">
	<% @users.each do |user| %>

	
	<div class="col-md-4">
		<a href="/users/<%=user.id%>">
			<div class="movie_frame">
				

				<% if user.user_img.file? %>

  					<%= image_tag user.user_img.url(:user_index), :class => "index_img_user"%>

				<% else %>
  					 <img class='index_img_user' src="/assets/default-user.png" >

				<% end %>
				
				
				<div class="inside">
	 				<%= user.firstname %> <%= user.surname %>

	 			</div>
	 		</div>
	 	</a>
	</div>

	<% end %>
</div>

MovieReview/app/views/users/show.html.erb
<a href="/movies/">
<img class='backbutton' src="/assets/back.jpg" >
</a>
<div class="row">
<div class="col-md-4">


<% if @user.user_img.file? %>

  	<%= image_tag @user.user_img.url(:user_show), :class => "profile_picture"%>

<% else %>
   <img class='profile_picture' src="/assets/default-user.png" >

<% end %>

	
</div>

<div class="col-md-4">
	
		<h2><%= @user.firstname %> <%= @user.surname %> </h2>
	<h3><%= @user.email %></h3>

	<h3><%= @user.current_sign_in_at %></h3>
	<p><%=@user.about_me%></p>
<%if @user.id == current_user.id %>
		 <%=link_to "Edit", edit_user_registration_path(@user)%>
		<%end%>

	
</div>
<div class="col-md-4">
	<%@follows.each do |follow|%>
	<div>
		<%=follow.firstname%>
	</div>
	<div>
		<%=follow.email%>
	</div>
<%end%>
</div>
</div>	

	<h3><%= @user.firstname %>'s reviews:<h3>
	<div class="row">
		
		<% @reviews.each do |review|%>
	
		<div class="col-md-4">
		<script>
  			function apiCall() {	
 			 	$.getJSON('https://www.omdbapi.com/?t='+ encodeURI('<%=review.movie.title%>')+'&apikey=847f91b9').then(function(response){
  				var image=response.Poster;
  			$('.index_img<%=review.movie.id%>').attr('src',image);
  				})	
 			 }
			apiCall()
		</script>
		<div class=movie_frame_user>

			<a href="/movies/<%=review.movie.id%>">
				<img class="index_img<%=review.movie.id%>" src="/assets/notavailable.jpg" height="200" width= "auto">
			</a>
			<div class="inside">
	 			<%=review.movie.title%>

			<div class = "review-rating" data-score= "<%= review.rating %>"" ></div>
	 		<%=review.comment%>
	 		

	 		</div>
		</div>
		</div>
		<%end%>

	
	

</div>
<%= paginate @reviews %>




<script>
	$('.review-rating').raty({
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		},
		path: '/assets/'
	});
</script>